### ISSUE TITLE
v-model its returns the hole object, want only the code

### ISSUE THREAD

**Issue by hellohasan** [abhimediratta/vue-multiselect-listbox#21]
Hello author,
thank you for the beautiful component.

I am facing a problem. 

that is on v-model its returns the hole object with label and code but I want it just to return the code only.

How I can do that please help me.

**Comment by emog** [comment]
You should handle this yourself. All components like this return the whole object. Just like the vue-multiselect or other select component.

**Comment by abhimediratta** [comment]
It does this now, please check. Closing this now
