### ISSUE TITLE
how to use custom css in search input and the list boxes itself ? 

### ISSUE THREAD

**Issue by stagnet** [abhimediratta/vue-multiselect-listbox#35]
![image](https://user-images.githubusercontent.com/52235699/122370778-fb10ab00-cf7c-11eb-8909-2c4732baac59.png)

Hi, can you tell me how can i change styles of the hover portion in the image above?
P.S. -  overall documentation is good as compare to other packages I've came across.
Thanks in advance.

**Comment by brktoker** [comment]
hi, this link https://abhimediratta.github.io/vue-multiselect-listbox/guide/css.html#styling-search-input-boxes help the solved problem  or node_modules =>  vue-multiselect-listbox under file dist/vue-multi-select-listbox.css package you can do whatever you want by making changes.

**Comment by stagnet** [comment]
thanks you very much, I am not remembering well but, when I use this package at start I was able to changes its style directly from style tag inside .vue file, but then its doesn't seems to work after some time, then yesterday I recheck this it's again working well...!
Is their is a some sort of but that you resolve recently, I wonder : *)
