### ISSUE TITLE
onOptionRemove function removes LAST item insted of TARGET item

### ISSUE THREAD

**Issue by julius-spudvilas** [abhimediratta/vue-multiselect-listbox#44]
https://github.com/abhimediratta/vue-multiselect-listbox/blob/439923fd84289027ee82e74f4d6a3d624a156968/src/components/MultiSelect/MultiSelect.vue#L210

There is issue here...

With complex objects when user tries to use "reduce-value-property" prop and passes function something like:
(option) => option.id

let valueIndex = items.findIndex((item) => {
        if (this.reduceValueProperty) {
          return item && option
          && (getValueFromOption(this.reduceValueProperty, item)
              === getValueFromOption(this.reduceValueProperty, option));
        }
        return item === option;
      });

getValueFromOption(this.reduceValueProperty, item)    <---- here item is already filtered ID, so you get UNDEFINED as you cant get ID from a string.
getValueFromOption(this.reduceValueProperty, option))  <---- here option is Object so you get back VALUE

**Comment by caesarleong** [comment]
Hi, can we have this bug fix release?

**Comment by abhimediratta** [comment]
Thanks for reporting the issue, published release with the fix
